const users = [
  {
    username: "user1",
    password: "password1",
    email: "user1@example.com",
    contactNumber: "1234567890",
    role: "user",
    user_id: "1",
    name: "Emma Johnson",
  },
  {
    username: "user2",
    password: "password2",
    email: "user2@example.com",
    contactNumber: "9876543210",
    role: "user",
    user_id: "2",
    name: "John Smith",
  },
  {
    username: "user3",
    password: "password3",
    email: "user3@example.com",
    contactNumber: "5678901234",
    role: "user",
    user_id: "3",
    name: "Sophia Williams",
  },
  {
    username: "user4",
    password: "password4",
    email: "user4@example.com",
    contactNumber: "0987654321",
    role: "user",
    user_id: "4",
    name: "Oliver Brown",
  },
  {
    username: "user5",
    password: "password5",
    email: "user5@example.com",
    contactNumber: "5432109876",
    role: "user",
    user_id: "5",
    name: "Emily Davis",
  },
  {
    username: "user6",
    password: "password6",
    email: "user6@example.com",
    contactNumber: "2468135790",
    role: "user",
    user_id: "6",
    name: "Michael Johnson",
  },
  {
    username: "user7",
    password: "password7",
    email: "user7@example.com",
    contactNumber: "9753108642",
    role: "user",
    user_id: "7",
    name: "Jennifer Thompson",
  },
  {
    username: "user8",
    password: "password8",
    email: "user8@example.com",
    contactNumber: "1357924680",
    role: "user",
    user_id: "8",
    name: "Daniel Wilson",
  },
  {
    username: "user9",
    password: "password9",
    email: "user9@example.com",
    contactNumber: "8642097531",
    role: "user",
    user_id: "9",
    name: "Sophia Davis",
  },
  {
    username: "user10",
    password: "password10",
    email: "user10@example.com",
    contactNumber: "3698521470",
    role: "user",
    user_id: "10",
    name: "Ethan Anderson",
  },
  {
    username: "user11",
    password: "password11",
    email: "user11@example.com",
    contactNumber: "7418529630",
    role: "user",
    user_id: "11",
    name: "Olivia Taylor",
  },
  {
    username: "user12",
    password: "password12",
    email: "user12@example.com",
    contactNumber: "2581470369",
    role: "user",
    user_id: "12",
    name: "Noah Thomas",
  },
  {
    username: "user13",
    password: "password13",
    email: "user13@example.com",
    contactNumber: "1230987654",
    role: "user",
    user_id: "13",
    name: "Ava Clark",
  },
  {
    username: "user14",
    password: "password14",
    email: "user14@example.com",
    contactNumber: "4567890123",
    role: "user",
    user_id: "14",
    name: "William Rodriguez",
  },
  {
    username: "user15",
    password: "password15",
    email: "user15@example.com",
    contactNumber: "9870123456",
    role: "user",
    user_id: "15",
    name: "Isabella Martinez",
  },
];

module.exports = users;
