const menu = [
  {
    id: 1,
    title: "Double Cheese Potato Burger",
    category: "Burger",
    price: 45,
    calories: "220 - 280 Kcal",
    image: "assets/images/burger.jpg",
    type: "veg",
  },
  {
    id: 2,
    title: "Cheese Sandwich",
    category: "Sandwich",
    price: 45,
    calories: "250 - 300 Kcal",
    image: "assets/images/sandwich1.jpg",
    type: "veg",
  },
  {
    id: 3,
    title: "Veg Club Sandwich",
    category: "Sandwich",
    price: 60,
    calories: "320 - 400 Kcal",
    image: "assets/images/s2.jpg",
    type: "veg",
  },
  {
    id: 4,
    title: "Cheese Masala Sandwich",
    category: "Sandwich",
    price: 45,
    calories: "250 - 300 Kcal",
    image: "assets/images/sandwich2.jpg",
    type: "veg",
  },
  {
    id: 5,
    title: "Veg Schezuan Sandwich",
    category: "Sandwich",
    price: 45,
    calories: "230 - 285 Kcal",
    image: "assets/images/schez-sandwich.jpg",
    type: "veg",
  },
  {
    id: 6,
    title: "Masala Maggie",
    category: "Maggie",
    price: 25,
    calories: "150 - 280 Kcal",
    image: "assets/images/maggie.jpg",
    type: "veg",
  },
  {
    id: 7,
    title: "Schezuan Maggie",
    category: "Maggie",
    price: 30,
    calories: "165 - 225 Kcal",
    image: "assets/images/maggie-s.jpg",
    type: "veg",
  },
  {
    id: 8,
    title: "Veg Maggie",
    category: "Maggie",
    price: 30,
    calories: "170 - 220 Kcal",
    image: "assets/images/veg-maggie.jpg",
    type: "veg",
  },
  {
    id: 9,
    title: "Cheese Garlic Maggie",
    category: "Maggie",
    price: 40,
    calories: "190 - 230 Kcal",
    image: "assets/images/garlic-maggie.jpg",
    type: "veg",
  },
  {
    id: 10,
    title: "Cheese Veg Maggie",
    category: "Maggie",
    price: 45,
    calories: "175 - 235 Kcal",
    image: "assets/images/cheese-maggie.jpg",
    type: "veg",
  },
  {
    id: 11,
    title: "Masala Fries",
    category: "Fries",
    price: 35,
    calories: "120 - 185 Kcal",
    image: "assets/images/frenchfries.jpg",
    type: "veg",
  },
  {
    id: 12,
    title: "Schezuan Fries",
    category: "Fries",
    price: 45,
    calories: "135 - 210 Kcal",
    image: "assets/images/shezuan.jpg",
    type: "veg",
  },
  {
    id: 13,
    title: "Cheese Fries",
    category: "Fries",
    price: 40,
    calories: "140 - 156 Kcal",
    image: "assets/images/cheese-fries.jpg",
    type: "veg",
  },
  {
    id: 14,
    title: "Red Sauce Pasta",
    category: "Pasta",
    price: 80,
    calories: "241 - 321 Kcal",
    image: "assets/images/pasta.jpg",
    type: "veg",
  },
  {
    id: 15,
    title: "White Sauce Pasta",
    category: "Pasta",
    price: 80,
    calories: "265 - 321 Kcal",
    image: "assets/images/white-pasta.jpg",
    type: "veg",
  },
  {
    id: 16,
    title: "Milk Shakes",
    category: "Beverages",
    price: 35,
    calories: "155 - 210 Kcal",
    image: "assets/images/milk-shake.jpg",
    type: "veg",
  },
  {
    id: 17,
    title: "Hot Chocolate",
    category: "Beverages",
    price: 35,
    calories: "230 - 280 Kcal",
    image: "assets/images/hot-coffee.jpg",
    type: "veg",
  },
  {
    id: 18,
    title: "Aerated Drinks",
    category: "Beverages",
    price: 10,
    calories: "260 - 365 Kcal",
    image: "assets/images/Aerated-Drinks.jpg",
    type: "veg",
  },
  {
    id: 19,
    title: "Cold Coffee",
    category: "Beverages",
    price: 35,
    calories: "255 - 360 Kcal",
    image: "assets/images/cold-coffee.jpg",
    type: "veg",
  },
  {
    id: 20,
    title: "Coffee",
    category: "Beverages",
    price: 15,
    calories: "220 - 265 Kcal",
    image: "assets/images/coffee.jpg",
    type: "veg",
  },
  {
    id: 21,
    title: "Tea",
    category: "Beverages",
    price: 10,
    calories: "155 - 225 Kcal",
    image: "assets/images/tea.jpg",
    type: "veg",
  },
  {
    id: 22,
    title: "Chocolate Frappe",
    category: "Beverages",
    price: 35,
    calories: "265 - 355 Kcal",
    image: "assets/images/beverage.jpg",
    type: "veg",
  },
  {
    id: 23,
    title: "Veg Puff",
    category: "Bakery",
    price: 35,
    calories: "260 - 320 Kcal",
    image: "assets/images/puff.jpg",
    type: "veg",
  },
  {
    id: 24,
    title: "Paneer Puff",
    category: "Bakery",
    price: 45,
    calories: "280 - 340 Kcal",
    image: "assets/images/puff-1.jpg",
    type: "veg",
  },
  {
    id: 25,
    title: "Veg Roll",
    category: "Bakery",
    price: 30,
    calories: "240 - 290 Kcal",
    image: "assets/images/roll.jpg",
    type: "veg",
  },
  {
    id: 26,
    title: "Cheese Roll",
    category: "Bakery",
    price: 40,
    calories: "280 - 330 Kcal",
    image: "assets/images/roll-1.jpg",
    type: "veg",
  },
];

module.exports = menu;
